Deepfake gen
BitMind-AI/bitmind-subnet pull request #14
Opened 2024-07-12 04:49 UTC by aliang322

Added subdirectory for synthetic image generation functionality and local dataset creation. Added demo python notebooks for real-image-to-text-annotation pipeline with BLIP-2 pretrained on COCO image dataset, and annotation-to-synthetic-image pipeline with different diffusion models. Updated validator to use the new pipelines for deepfake detection inference on synthetic images.

2024-07-13 01:11 UTC, dylanuys requested changes

2024-07-13 01:11 UTC, dylanuys commented on bitmind/synthetic_image_generation/README.md
> +
shall we move this to the main README directory hierarchy breakdown rather than having disparate READMEs? Open to restructuring that, but all the other dirs are currenlty described in the main README.

2024-07-13 01:11 UTC, dylanuys commented on bitmind/validator/forward.py
> +                real_sample, source_name, image_index=image_index,
`source_name` isn't defined at this point - based on the intended usage you'll have to modify the `_get_image` function in `real_image_dataset.py` to also return the name of the dataset and access it in `real_sample` (which in general feels like a good addition to the returned dictionary there)

2024-07-13 01:11 UTC, dylanuys commented on bitmind/synthetic_image_generation/synthetic_image_generator.py
> +            img_filename = f"{save_dir}/{prompt[:50].replace(' ', '_').replace('/', '_').replace('\\', '_')}-{index}.png"
`save_dir` is undefined

2024-07-13 01:32 UTC, dylanuys commented
In a subsequent PR, lets also refactor `SyntheticImageGenerator` and `RandomImageGenerator` into once class (i like the name `SyntheticImageGenerator` for this) that parameterizes the prompt generation technique

2024-07-15 16:37 UTC, aliang322 commented on bitmind/synthetic_image_generation/README.md
> +
Yes lets aggregate and move the content out of the subdir. Will commit

2024-07-15 18:12 UTC, aliang322 commented on bitmind/validator/forward.py
> +                real_sample, source_name, image_index=image_index,
I removed a redundant data util `sample_image_with_index()` and replaced with `sample_dataset_index_name()` in a new commit. The util addresses this by returning a random `ImageDataset`'s index and it's associated dataset source name from a list of `ImageDataset`s.

2024-07-15 18:24 UTC, aliang322 commented on bitmind/synthetic_image_generation/synthetic_image_generator.py
> +            img_filename = f"{save_dir}/{prompt[:50].replace(' ', '_').replace('/', '_').replace('\\', '_')}-{index}.png"
Fixed by @benliang99 in [](https://github.com/BitMind-AI/bitmind-subnet/pull/14/commits/50a27b0d409a314245e36b01d47bde54f032c9d7)

2024-07-15 18:36 UTC, aliang322 commented on bitmind/synthetic_image_generation/README.md
> +
I think we can do this in a following PR actually, as we have readme changes in Main to merge with @dylanuys

2024-07-16 15:08 UTC, benliang99 approved these changes
Looks like everything was addressed.

2024-07-16 15:44 UTC, dylanuys approved these changes

2024-07-16 15:44 UTC, merged